/*
CREATE TABLE USUARIO(
	ID				UNIQUEIDENTIFIER		NOT NULL,
	NOME			NVARCHAR(150)			NOT NULL,
	EMAIL			NVARCHAR(150)			NOT NULL UNIQUE,
	SENHA			NVARCHAR(50)			NOT NULL,
	DATAINCLUSAO	DATETIME				NOT NULL,
	PRIMARY KEY(ID))
GO


--MODIFICANDO A TABELA DE EVENTO
--PARA ADICIONAR O CAMPO 'IDUSUARIO'
ALTER TABLE EVENTO ADD
IDUSUARIO UNIQUEIDENTIFIER
GO

--MODIFICANDO A TABELA DE EVENTO
--PARA DEFINIR O CAMPO 'IDUSUARIO' COMO CHAVE ESTRANGEIRA

ALTER TABLE EVENTO ADD CONSTRAINT FK_USUARIO
FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID)
GO

select * from usuario

select * from evento;
*/
SELECT 
                       * 
                FROM 
                     EVENTO
                WHERE 
                     ATIVO = 1 AND 
                    -- DATA BETWEEN  '2022-02-18' AND  '2022-01-29' AND 
                     IDUSUARIO = 'C42FB680-B289-4FD5-8010-AAC3CF6D67EA'
                ORDER BY DATA DESC, HORA DESC;
